apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudacademy-web-apis
  namespace: cloudacademy
  labels:
    app: cloudacademy-web-apis
    component: backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudacademy-web-apis
  template:
    metadata:
      labels:
        app: cloudacademy-web-apis
        component: backend
        tier: api
    spec:
      containers:
      - name: web-apis
        image: registry.cloud-it.com.ar/api-web-cloudacademy:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: cloudacademy-web-apis-secret
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudacademy-web-apis-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudacademy-web-apis-secret
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cloudacademy-web-apis-secret
              key: db-name
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: cloudacademy-web-apis-secret
              key: db-port
        - name: LOG_LEVEL
          value: "INFO"
        - name: SERVICE_NAME
          value: "cloudacademy-web-apis"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      imagePullSecrets:
      - name: registry-secret
      securityContext:
        fsGroup: 1000